import Chats_component from "./Chats_component";
import Chat_section from "./Chat_section";

export const Chats = [
    {
        name: "Sahil_khatri",
        dp: "./images/sahil_dp.jpg",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: true,
                is_sent: true,
                is_delivered: true,
                is_seen: true,
                is_text: false,
                is_audio: false,
                audio_duration: "0:02",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "thik ha",
                time: "14:55",
            }
    },
    {
        name: "Aman",
        dp: "",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: false,
                is_sent: true,
                is_delivered: true,
                is_seen: true,
                is_text: false,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "thik ha",
                time: "yesterday",
            }
    },
    {
        name: "Rishi_mam",
        dp: "./images/rishi_mam_dp.jfif",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: true,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: true,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "Ok mam",
                time: "yesterday",
            }
    },
    {
        name: "Nayan Roy",
        dp: "./images/nayan_roy_dp.jpg",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: true,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: true,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "ok bro",
                time: "yesterday",
            }
    },
    {
        name: "Daya_Sagar_Office",
        dp: "./images/daya_dp.jpg",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: false,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: true,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "Bhai ram ji ka no ha kya",
                time: "yesterday",
            }
    },
    {
        name: "Anas Khan",
        dp: "./images/anas_dp.enc",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: false,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: true,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "Jo form bharega usko free transport milega",
                time: "yesterday",
            }
    },
    {
        name: "Harsh_sir",
        dp: "./images/harsh_sir_dp.jfif",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: false,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: true,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: true,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "okay",
                time: "yesterday",
            }
    },
    {
        name: "Kampodar Mama",
        dp: "./images/km.jpg",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: false,
                is_sent: true,
                is_delivered: true,
                is_seen: false,
                is_text: false,
                is_audio: false,
                audio_duration: "",
                is_video: true,
                is_document: false,
                document_name: "",
                is_sticker: false,
                is_image: false,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "okay",
                time: "05/03/2023",
            }
    },
    {
        name: "Arman (You)",
        dp: "./images/dp.jfif",
        is_online: true,
        last_seen: "12:00",
        last_message: {
                is_sent_by_me: true,
                is_sent: true,
                is_delivered: true,
                is_seen: true,
                is_text: false,
                is_audio: false,
                audio_duration: "",
                is_video: false,
                is_document: true,
                document_name: "whatsapp_web_copy_zip.zip",
                is_sticker: false,
                is_image: false,
                is_gif: false,
                is_contact: false,
                is_location: false,
                is_audio_call: false,
                is_video_call: false,
                message: "okay",
                time: "05/03/2023",
            }
    },
]

function Chats_details() {
    var data = "";
    function setContactName(name) {
        data = name;
    }

    return(
        <div>
            <Chats_component  
            // code to pass the data to the chats component
            contact={setContactName}

            />
            <Chat_section contact_name={data}/>
        </div>
    )
}
export default Chats_details;